pool:
  vmImage: vs2017-win2016
  demands: maven

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - powershell: |
      $s = @{
          "o" = "$(system.teamOrganization)"
          "t" = "$(system.teamToken)"
          "p" = "$(system.teamProject)"
      } | ConvertTo-Json

      $f = Get-ChildItem -Path $PWD.Path -Filter "_unitTest.json" -Recurse
      $pom = Get-ChildItem -Path $PWD.Path -Filter "pom.xml" -Recurse

      $s| Set-Content -Path $f.FullName -Encoding UTF8

    displayName: 'PowerShell Script'
    enabled: false

  - task: Maven@3
    displayName: 'Maven azd/pom.xml'
    inputs:
      mavenPomFile: azd/pom.xml
      goals: package
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      jdkVersionOption: 1.11
      javaHomeOption: JDKVersion

  - task: CopyFiles@2
    displayName: 'Copy jar file'
    inputs:
      Contents: '**/*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'