name: $(Build.BuildID)

trigger:
  - main

stages:
  - stage: Build

    jobs:
      - job: Linux

    pool:
      vmImage: 'ubuntu-16.04'
      demands: maven
    
      steps:
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '11'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'
      
        - powershell: |
            $s = @{
                "o" = "$(system.teamOrganization)"
                "t" = "$(system.teamToken)"
                "p" = "$(system.teamProject)"
            } | ConvertTo-Json
      
            $f = Get-ChildItem -Path $PWD.Path -Filter "_unitTest.json" -Recurse
            $pom = Get-ChildItem -Path $PWD.Path -Filter "pom.xml" -Recurse
      
            $s| Set-Content -Path $f.FullName -Encoding UTF8
      
          displayName: 'PowerShell Script'
          enabled: true
      
        - task: Maven@3
          displayName: 'Maven azd/pom.xml'
          inputs:
            mavenPomFile: azd/pom.xml
            goals: test
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'